### ISSUE TITLE
Questions Regarding ICOR Preprint

### ISSUE THREAD

**Issue by RJain12** [Lattice-Automation/icor-codon-optimization#4]
I am answering the following questions asked by @SandhiyaRa

1. File named ‘optimum.csv’ / 'optimum_genes.csv'

As explained in the comments of the code, this is a CSV file that is generated by GenScript's Tool that contains the sequences. If you want to generate this file, you can input sequences into their website manually. The sequences that we used in our study have already been converted into [FASTA sequence files](https://github.com/Lattice-Automation/icor-codon-optimization/tree/main/benchmark_sequences/genscript).

2. How is the benchmark results computed for ICOR tool?

All of the benchmark results including those of the ICOR tool were generated by our [benchmarking script](https://github.com/Lattice-Automation/icor-codon-optimization/blob/main/tool/scripts/run_benchmark.ipynb).

3. Training and testing dataset availability?

As mentioned in the manuscript, our datasets were retrieved from the NCBI. This data was partitioned and processed as per the methodology outlined in the manuscript: "24. National Center for Biotechnology Information. Genome Escherichia coli. Bethesda [Internet]. 2021. Available from: ftp://ftp.ncbi.nlm.nih.gov/genomes/refseq/bacteria/Escherichia_coli"

Hope this is helpful!

**Comment by SandhiyaRa** [comment]
Thank you @RJain12  for adding the questions here.

**Comment by SandhiyaRa** [comment]
Few questions on the model:

1. Could you share the ICOR model [raw] and implementation details [like how it was created and trained]?

2. How's the table.3 recorded?

3. Could you share details of the usage of NLFT in the code?

- Thanks

**Comment by RJain12** [comment]
Resolved
