### ISSUE TITLE
ONNXRuntimeError NO_SUCHFILE for icor.onnx?

### ISSUE THREAD

**Issue by erynes** [Lattice-Automation/icor-codon-optimization#5]
Hi, I followed the "quickstart" instructions and ran icor_optimizer.py and input a sequence, but I'm getting the ONNXRuntimeError NO_SUCHFILE for icor.onnx. I'm running on OSX, so I changed `model_path` (with backslashes in it) to point to where my copy of icor.onnx resides, but this didn't solve it. What can I do to run it?

`sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.NoSuchFile: [ONNXRuntimeError] : 3 : NO_SUCHFILE : Load model from ~/repos/icor-codon-optimization/tool/models/icor.onnx  failed:Load model ~/repos/icor-codon-optimization/tool/models/icor.onnx  failed. File doesn't exist`

despite:

`$ ls -1 ~/repos/icor-codon-optimization/tool/models/icor.onnx >/dev/null ; echo $?`
0

**Comment by RJain12** [comment]
According to the ONNX documentation, this error is not internal within the ONNX runtime. Rather, it is exactly what it states -- the file does not exist. 

You are correct in that OSX would use forward slashes in the `model_path`.

The code sets the following:
```
model_path = r"..\..\tool\models\icor.onnx"
```
This should provide a path to the icor.onnx model file relative to the optimization file. When tested in the Ubuntu environment, the code works fine without any error.

I raise the following suggestions which I hope will help address your issue:
1. When installing the repository onto your machine, was the entire repository including the `icor.onnx` file retrieved?
2. When using your file explorer/finder, is the icor.onnx file in the same spot as you set for `model_path`?
3. Adding onto suggestion 2 above, when you try to go to `~/repos/icor-codon-optimization/tool/models/` outside of the Python environment, i.e. in your file explorer/finder, is the `icor.onnx` model file present?
4. Are you running this code on a virtual machine or Python virtualenv? If so, can you double-check to make sure the model file is present and/or available in this environment?
5. In a separate Python shell, can you try navigating to the `/tool/models/` directory and then checking if the file exists using `os.path.exists`?

Hopefully these help!

**Comment by RJain12** [comment]
In the latest update of the ICOR code, relative pathing is used via the "os" package. This should resolve any OS-based issues.
