### ISSUE TITLE
The  consult question

### ISSUE THREAD

**Issue by yaolp123** [Lattice-Automation/icor-codon-optimization#7]
Dear github author:
   Recently I have read your project and am interested in it, and I also have a question that, where could I open icor.onnx this model or could I find the original matlab code of this model icor？  I am looking forward to your letter. 

Best regards.

**Comment by RJain12** [comment]
Hello @yaolp123, the ICOR.onnx model file is open source and included in this GitHub repository.

Please find it here: https://github.com/Lattice-Automation/icor-codon-optimization/tree/main/tool/models

The details for how this model were trained in MATLAB are included in the paper. You can view our preprint here:
https://www.biorxiv.org/content/10.1101/2021.11.08.467706v3

**Comment by yaolp123** [comment]
Dear github authors:


&nbsp; I am pleased to hear from your reply. Thank you for your replay. And I want to further consult is that, the implement program of ICOR.onnx model, how could I find that?&nbsp;&nbsp;https://github.com/Lattice-Automation/icor-codon-optimization/tree/main/tool/models&nbsp;this include the&nbsp;icor.onnx,but the implement program, I&nbsp;seems could not open or find it.&nbsp; I am looking forward to your reply.&nbsp; Thank you very much.




Best regards.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Lattice-Automation/icor-codon-optimization"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月11日(星期二) 上午7:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Lattice-Automation/icor-codon-optimization] The  consult question (Issue #7)





 
Hello @yaolp123, the ICOR.onnx model file is open source and included in this GitHub repository.
 
Please find it here: https://github.com/Lattice-Automation/icor-codon-optimization/tree/main/tool/models
 
The details for how this model were trained in MATLAB are included in the paper. You can view our preprint here:
 https://www.biorxiv.org/content/10.1101/2021.11.08.467706v3

**Comment by RJain12** [comment]
To run/use the ICOR.onnx model, please use the ICOR_optimizer.py script in Python:
https://github.com/Lattice-Automation/icor-codon-optimization/blob/main/tool/optimizers/icor_optimizer.py
